# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/router/Desktop/vscode_workplace/libmyEvent

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/router/Desktop/vscode_workplace/libmyEvent

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/router/Desktop/vscode_workplace/libmyEvent/CMakeFiles /home/router/Desktop/vscode_workplace/libmyEvent/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/router/Desktop/vscode_workplace/libmyEvent/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

channel.o: channel.cc.o

.PHONY : channel.o

# target to build an object file
channel.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/channel.cc.o
.PHONY : channel.cc.o

channel.i: channel.cc.i

.PHONY : channel.i

# target to preprocess a source file
channel.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/channel.cc.i
.PHONY : channel.cc.i

channel.s: channel.cc.s

.PHONY : channel.s

# target to generate assembly for a file
channel.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/channel.cc.s
.PHONY : channel.cc.s

epoller.o: epoller.cc.o

.PHONY : epoller.o

# target to build an object file
epoller.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/epoller.cc.o
.PHONY : epoller.cc.o

epoller.i: epoller.cc.i

.PHONY : epoller.i

# target to preprocess a source file
epoller.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/epoller.cc.i
.PHONY : epoller.cc.i

epoller.s: epoller.cc.s

.PHONY : epoller.s

# target to generate assembly for a file
epoller.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/epoller.cc.s
.PHONY : epoller.cc.s

eventloop.o: eventloop.cc.o

.PHONY : eventloop.o

# target to build an object file
eventloop.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/eventloop.cc.o
.PHONY : eventloop.cc.o

eventloop.i: eventloop.cc.i

.PHONY : eventloop.i

# target to preprocess a source file
eventloop.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/eventloop.cc.i
.PHONY : eventloop.cc.i

eventloop.s: eventloop.cc.s

.PHONY : eventloop.s

# target to generate assembly for a file
eventloop.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/eventloop.cc.s
.PHONY : eventloop.cc.s

listener.o: listener.cc.o

.PHONY : listener.o

# target to build an object file
listener.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/listener.cc.o
.PHONY : listener.cc.o

listener.i: listener.cc.i

.PHONY : listener.i

# target to preprocess a source file
listener.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/listener.cc.i
.PHONY : listener.cc.i

listener.s: listener.cc.s

.PHONY : listener.s

# target to generate assembly for a file
listener.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/listener.cc.s
.PHONY : listener.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.s
.PHONY : main.cc.s

tcpserver.o: tcpserver.cc.o

.PHONY : tcpserver.o

# target to build an object file
tcpserver.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tcpserver.cc.o
.PHONY : tcpserver.cc.o

tcpserver.i: tcpserver.cc.i

.PHONY : tcpserver.i

# target to preprocess a source file
tcpserver.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tcpserver.cc.i
.PHONY : tcpserver.cc.i

tcpserver.s: tcpserver.cc.s

.PHONY : tcpserver.s

# target to generate assembly for a file
tcpserver.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tcpserver.cc.s
.PHONY : tcpserver.cc.s

thread_pool.o: thread_pool.cc.o

.PHONY : thread_pool.o

# target to build an object file
thread_pool.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/thread_pool.cc.o
.PHONY : thread_pool.cc.o

thread_pool.i: thread_pool.cc.i

.PHONY : thread_pool.i

# target to preprocess a source file
thread_pool.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/thread_pool.cc.i
.PHONY : thread_pool.cc.i

thread_pool.s: thread_pool.cc.s

.PHONY : thread_pool.s

# target to generate assembly for a file
thread_pool.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/thread_pool.cc.s
.PHONY : thread_pool.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... channel.o"
	@echo "... channel.i"
	@echo "... channel.s"
	@echo "... epoller.o"
	@echo "... epoller.i"
	@echo "... epoller.s"
	@echo "... eventloop.o"
	@echo "... eventloop.i"
	@echo "... eventloop.s"
	@echo "... listener.o"
	@echo "... listener.i"
	@echo "... listener.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tcpserver.o"
	@echo "... tcpserver.i"
	@echo "... tcpserver.s"
	@echo "... thread_pool.o"
	@echo "... thread_pool.i"
	@echo "... thread_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

